name: Lint & Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-format:
    name: Lint, Format, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy

      - name: Run black
        run: black .

      - name: Run isort
        run: isort .

    #   - name: Run mypy
    #     run: mypy .
